In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_percentage_error,mean_absolute_error
import yfinance as yf

In [4]:
df = yf.download("AAPL", start = "2015-01-01", end= "2026-04-09")
df.to_csv("AAPL.csv")

[*********************100%***********************]  1 of 1 completed

In [5]:
df.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2015-01-02  24.214897  24.682230  23.776357  24.671155  212818400
2015-01-05  23.532719  24.064282  23.346673  23.984547  257142000
2015-01-06  23.534935  23.794071  23.173914  23.596950  263188400
2015-01-07  23.864946  23.964614  23.632387  23.743129  160423600
2015-01-08  24.781898  24.839485  24.075362  24.192751  237458000

In [9]:
df.tail()

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2026-04-01  255.630005  256.179993  253.330002  254.080002  40059400
2026-04-02  255.919998  256.130005  250.649994  254.199997  31289400
2026-04-06  258.859985  262.160004  256.459991  256.510010  29329900
2026-04-07  253.500000  256.200012  245.699997  256.160004  62148000
2026-04-08  258.899994  259.750000  256.529999  258.450012  41032800

In [6]:
df.shape

(2832, 5)

In [7]:
df.describe()

Price         Close         High          Low         Open        Volume
Ticker         AAPL         AAPL         AAPL         AAPL          AAPL
count   2832.000000  2832.000000  2832.000000  2832.000000  2.832000e+03
mean     109.806183   110.903418   108.612256   109.718280  1.099094e+08
std       76.967196    77.720095    76.154356    76.909880  6.797401e+07
min       20.584808    20.887868    20.386572    20.507344  1.791060e+07
25%       37.097627    37.428632    36.689749    37.080098  6.311622e+07
50%      107.174046   109.047812   105.552699   107.231079  9.310420e+07
75%      171.083988   172.144465   169.009016   170.646415  1.357272e+08
max      285.922455   288.350192   283.035157   285.932471  6.488252e+08

In [8]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2832 entries, 2015-01-02 to 2026-04-08
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   2832 non-null   float64
 1   (High, AAPL)    2832 non-null   float64
 2   (Low, AAPL)     2832 non-null   float64
 3   (Open, AAPL)    2832 non-null   float64
 4   (Volume, AAPL)  2832 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 132.8 KB